# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMjTbYjthz3smaVvjA8dZDJZ2H6WvHq9
"""

pip install streamlit

import streamlit as st

analistas = ['Débora','Marcel', 'Raul', 'Vinícius']

st.selectbox('Selecione o analista: ',['Todos'] + analistas)

